### ISSUE TITLE
compile whith GCC 8.4.0 

### ISSUE THREAD

**Issue by blithe2015** [willamowius/ptlib#12]
ptlib/unix/ptlib/pmachdep.h:56:13: error: conflicting declaration 'typedef int socklen_t'
bits/alltypes.h:394:18: note: previous declaration as 'typedef unsigned int socklen_t'  typedef unsigned socklen_t;

**Comment by willamowius** [comment]
I have seen GCC 8 work at least on some Linux distributions. What OS / version do you see this issue on ?

**Comment by blithe2015** [comment]
ubuntu 18.04 , compile openwrt ,package version at : 6411e778be5bb99720e79d6710bcd18c697ae476

**Comment by willamowius** [comment]
Hmm, my Ubuntu 18.04 ships with GCC 7.4.0 which compiles PTLib fine and I don't see a GCC 8 packet in the Ubuntu repo.
Also, I don't see where https://github.com/openwrt/openwrt is using PTLib.

**Comment by blithe2015** [comment]
It seems that the version at that time is indeed not compatible with gcc8.0 and above. Many glibc functions have been abandoned.

**Comment by willamowius** [comment]
Please update to the current version.
