### ISSUE TITLE
Supporting OpenLDAP 2.5 or newer

### ISSUE THREAD

**Issue by brad0** [willamowius/ptlib#21]
Looking at PTLIB_FIND_OPENLDAP in ptlib.m4..

```
          if test "x${ptlib_openldap}" = "xyes"; then  
            case "$target_os" in
            solaris* | sunos* )
                            dnl posix4 is required by libldap_r on Solaris
                            ptlib_openldap_libs="-lposix4"
                            ;;
                            * )
                            ptlib_openldap_libs="-llber -lldap_r"
            esac
```

The macro hardcodes libldap_r for OpenLDAP. OpenLDAP 2.5 and newer has eliminated the libdap_r library and merged that into libldap. I'm not sure how you would want to deal with that. The OpenBSD port just has a diff to s/ldap_r/ldap/ but of course something better is necessary

**Comment by willamowius** [comment]
I don't know of any application using the LDAP support in PTLib and I don't think it really belongs in there anyway.
Unless you have an application that needs it, I would tend depreciate it and stop building it by default if its causing any kind of issues.

**Comment by brad0** [comment]
Ah, I was looking at our ptlib port and noticed it had OpenLDAP as a dependency and with this recent patch added. Looking at the tree the only dependency I see using ptlib is h323plus.

**Comment by willamowius** [comment]
H323Plus isn't using LDAP at all.

**Comment by willamowius** [comment]
H.350 for which LDAP is used never really caught on so it would be fine to build PTLib without LDAP.
If you want to keep LDAP alive on OpenBSD, send a pull request for configure.in.

**Comment by brad0** [comment]
I think it makes more sense to disable the LDAP support if it's truely not being used. If it's a fork of PTlib just for H323Plus why not remove that bit?

**Comment by willamowius** [comment]
There is no gain in removing the code. We can let configure fail in the detection for now.

**Comment by brad0** [comment]
I disabled the OpenLDAP support in the ptlib port.

https://marc.info/?l=openbsd-ports-cvs&m=166532629218883&w=2
