### ISSUE TITLE
Inconsistent definitions of `operator new[]`/`operator delete[]`

### ISSUE THREAD

**Issue by Lastique** [willamowius/ptlib#34]
In commit https://github.com/willamowius/ptlib/commit/87728760efd5dc966374ff65e0e97b1cf5d7e6ed, the signature of `operator new[]` has been changed to include `std::align_val_t` argument on a C++17 compiler. However, the signature of `operator delete[]` was *not* changed and remains without the `std::align_val_t` argument, which means it will *not* be called when the type of the object being deleted is over-aligned (i.e. when the overloaded `operator new[]` *was* called to allocate it).

Furthermore, the `operator new[]` does not use its `std::align_val_t` argument to ensure that the allocated memory is actually aligned to the value of `std::align_val_t`.

Relevant piece of code:

https://github.com/willamowius/ptlib/blob/c01afdc78cc4fb56e497b04aea69ef575fc53bf0/src/ptlib/common/object.cxx#L952-L972

Either both `operator new[]` and `operator delete[]` should accept (and use) the `std::align_val_t` argument, or none should. Lastly, in order to use `std::align_val_t`, `<new>` must be included, and this include is missing in `object.cxx`.

Relevant documentation for memory allocation functions:

https://en.cppreference.com/w/cpp/memory/new/operator_new
https://en.cppreference.com/w/cpp/memory/new/operator_delete

**Comment by Lastique** [comment]
Actually, could you explain the purpose of these overrides? As far as I can see, the main effect they had before the change was that they suppressed throwing `std::bad_alloc`. Is this the intention? If so, why?

Note that overriding global allocation functions affects all allocations, including those in the standard library and user's code. The standard definition of `operator new[]` that doesn't accept `std::nothrow_t` are specified to throw on failure, which means any code that uses them (which is practically any code calling `new`) would be broken by this non-conforming override.

Lastly, why `operator new[]` is overloaded but `operator new` isn't?

**Comment by willamowius** [comment]
Do you have a compiler that complains about this ?

We are very late in the life cycle of PTLib and the main purpose of this branch is to keep the interface and behaviour as closely as possible to what it was about 25 years ago to support OpenH323, H323Plus and all old apps that rely on it.

I try to change as little as possible and only if there is a demostratable issue.

Feel free to submit a patch to change the signature of the allocators accross the different C++ versions, but please test it it with a range of compilers.

From what I remember, the purpose of the allocators was to add memory debugging facilities back in the days when we didn't have tools like Valgrind, but I might be wrong.

**Comment by Lastique** [comment]
> Do you have a compiler that complains about this ?

I don't think compilers warn about inconsistent definitions of `new`/`delete`, and they also don't necessarily warn about definitions that that don't match the behavior mandated by the standard. That doesn't mean these definitions are not incorrect.

Here's a reproducer that shows that the operator mismatch is actually a bug:

```
#include <new>
#include <iostream>

char buf[128];

void* operator new[](std::size_t nSize, std::align_val_t al) noexcept(false)
{
    std::cout << "Called custom operator new[](" << nSize << ", " << static_cast< std::size_t >(al) << ")" << std::endl;
    if (nSize > 128)
        return nullptr;
    return buf;
}

void operator delete[](void * ptr) throw ()
{
    std::cout << "Called custom operator delete[]()" << std::endl;
    if (ptr != buf)
        std::cout << "Wrong ptr passed to the custom operator delete[]()" << std::endl;
}

struct alignas(32) overaligned {};

int main()
{
    overaligned* p = new overaligned[2];
    delete[] p;
}
```

```
$ g++ -std=c++17 -o test_operator_mismatch test_operator_mismatch.cpp 
test_operator_mismatch.cpp: In function ‘void* operator new [](std::size_t, std::align_val_t)’:
test_operator_mismatch.cpp:10:16: warning: ‘operator new’ must not return NULL unless it is declared ‘throw()’ (or ‘-fcheck-new’ is in effect)
   10 |         return nullptr;
      |                ^~~~~~~

lastique@lastique-pc:~/src/tmp$ ./test_operator_mismatch
Called custom operator new[](64, 32)
free(): invalid pointer
Aborted (core dumped)
```

(The compiler did warn about returning `nullptr` from `operator new` in this case because the return is immediately visible. It won't necessarily warn if the returned value is obtained from an external function call, such as `malloc`.)

The code crashes because the compiler calls `operator delete[] (void*, std::align_val_t)` in the standard library, which defers to `free`.

**Comment by Lastique** [comment]
I still think the operators should better be removed as they serve no purpose. Failing that, the operator signatures should be made consistent.

**Comment by Lastique** [comment]
> I try to change as little as possible and only if there is a demostratable issue.

In this case, you should probably revert the addition of the `std::align_val_t` argument.

**Comment by willamowius** [comment]
I updated memcheck when it is enabled for C++17 and removed the own new and delete implementations when memcheck is disabled.

**Comment by Lastique** [comment]
Thanks.
