### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by JustLooKeD** [willamowius/ptlib#8]
/u/l/s/ptlib-master# make
make DEBUG= P_SHAREDLIB=1 default_target
make[1]: вход в каталог «/usr/local/src/ptlib-master»
make[1]: выход из каталога «/usr/local/src/ptlib-master»
make[1]: вход в каталог «/usr/local/src/ptlib-master/src»
make DEBUG= P_SHAREDLIB=1 default_target
make[2]: вход в каталог «/usr/local/src/ptlib-master/src»
[CC] ptclib/psasl.cxx
[CC] ptclib/pldap.cxx
[CC] ptclib/pils.cxx
[CC] ptclib/pssl.cxx
ptclib/pssl.cxx:748:13: предупреждение: «void LockingCallback(int, int, const char*, int)» определена, но не используется [-Wunused-function]
 static void LockingCallback(int mode, int n, const char * /*file*/, int /*line*/)
             ^~~~~~~~~~~~~~~
[CC] ptclib/podbc.cxx
In file included from /usr/include/sql.h:19,
                 from /usr/include/odbcinst.h:22,
                 from /usr/local/src/ptlib-master/include/ptclib/podbc.h:100,
                 from ptclib/podbc.cxx:39:
/usr/include/sqltypes.h:105:26: ошибка: конфликтующая декларация «typedef short unsigned int WCHAR»
 typedef unsigned short   WCHAR;
                          ^~~~~
In file included from /usr/local/src/ptlib-master/include/ptlib/object.h:44,
                 from /usr/local/src/ptlib-master/include/ptlib/psync.h:43,
                 from /usr/local/src/ptlib-master/include/ptlib/critsec.h:34,
                 from /usr/local/src/ptlib-master/include/ptlib/contain.h:42,
                 from /usr/local/src/ptlib-master/include/ptlib.h:56,
                 from ptclib/podbc.cxx:35:
/usr/local/src/ptlib-master/include/ptlib/unix/ptlib/contain.h:96:33: замечание: предыдущая декларация «typedef wchar_t WCHAR»
 typedef wchar_t                 WCHAR;
                                 ^~~~~
In file included from /usr/include/sql.h:19,
                 from /usr/include/odbcinst.h:22,
                 from /usr/local/src/ptlib-master/include/ptclib/podbc.h:100,
                 from ptclib/podbc.cxx:39:
/usr/include/sqltypes.h:272:33: ошибка: конфликтующая декларация «typedef unsigned int UINT»
 typedef unsigned int            UINT;
                                 ^~~~
In file included from /usr/local/src/ptlib-master/include/ptlib/object.h:44,
                 from /usr/local/src/ptlib-master/include/ptlib/psync.h:43,
                 from /usr/local/src/ptlib-master/include/ptlib/critsec.h:34,
                 from /usr/local/src/ptlib-master/include/ptlib/contain.h:42,
                 from /usr/local/src/ptlib-master/include/ptlib.h:56,
                 from ptclib/podbc.cxx:35:
/usr/local/src/ptlib-master/include/ptlib/unix/ptlib/contain.h:86:22: замечание: предыдущая декларация «typedef uintptr_t UINT»
 typedef uintptr_t    UINT;
                      ^~~~
ptclib/podbc.cxx: В функции-члене «PString PODBC::Field::AsString()»:
ptclib/podbc.cxx:489:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:491:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.sbint);
           ^~~~~~
ptclib/podbc.cxx:495:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:497:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.sbit);
           ^~~~~~
ptclib/podbc.cxx:500:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:502:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.suchar);
           ^~~~~~
ptclib/podbc.cxx:505:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:507:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.slint);
           ^~~~~~
ptclib/podbc.cxx:510:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:512:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.ssint);
           ^~~~~~
ptclib/podbc.cxx:519:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:521:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.sdoub,Decimals);
           ^~~~~~
ptclib/podbc.cxx:525:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:527:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.date);
           ^~~~~~
ptclib/podbc.cxx:530:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:532:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return Convert(b.time);
           ^~~~~~
ptclib/podbc.cxx:535:10: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
          if (B)
          ^~
ptclib/podbc.cxx:537:12: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
            return Convert(b.timestamp);
            ^~~~~~
ptclib/podbc.cxx:540:10: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
          if (B)
          ^~
ptclib/podbc.cxx:542:12: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
            return Convert(b.guid);
            ^~~~~~
ptclib/podbc.cxx:556:9: предупреждение: эта «if» клаузула не защищает... [-Wmisleading-indentation]
         if (B)
         ^~
ptclib/podbc.cxx:558:11: замечание: ...этот оператор, но последний ошибочно полагается на защиту «if»
           return b.sbin;
           ^~~~~~
ptclib/podbc.cxx: В функции-члене «void PODBCRecord::Data(PINDEX, PODBC::Field&)»:
ptclib/podbc.cxx:1332:72: предупреждение: приведение к типу указателя от целого другого размера [-Wint-to-pointer-cast]
               SQLBindCol(m_hStmt, Column, SQL_LONGVARCHAR, (SQLPOINTER)Column, 0, &b.dataLen);
                                                                        ^~~~~~
make[2]: *** [../make/common.mak:97: /usr/local/src/ptlib-master/lib_linux_x86_64/obj/podbc.o] Ошибка 1
make[2]: выход из каталога «/usr/local/src/ptlib-master/src»
make[1]: *** [../make/common.mak:292: optshared] Ошибка 2
make[1]: выход из каталога «/usr/local/src/ptlib-master/src»
make: *** [Makefile:91: optshared] Ошибка 2

CentOS 8 4.18.0-240.10.1.el8_3.x86_64

**Comment by willamowius** [comment]
ODBC support in PTLib should be considered deprecated. With your version, you should use ./configure --disable-odbc.
I have disabled building ODBC support by default now.
